# Generated by Django 6.0.5 on 2026-05-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0005_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='COMPRA',
        ),
    ]
