# Generated by Django 6.0.5 on 2026-05-28 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0006_alter_proveedor_options_proveedor_foto_evidencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMetal',
            fields=[
                ('id_metal', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TIPO_METAL',
            },
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='foto_evidencia',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='observaciones',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='PROVEEDOR',
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('numero_acta_pdi', models.CharField(blank=True, max_length=50, null=True)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('forma_pago', models.CharField(default='Efectivo', max_length=50)),
                ('estado', models.CharField(default='Emitido', max_length=30)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.PROTECT, to='reciclaje.proveedor')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='reciclaje.usuario')),
            ],
            options={
                'db_table': 'COMPRA',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('metal_nombre', models.CharField(max_length=100)),
                ('peso_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, to='reciclaje.compra')),
            ],
            options={
                'db_table': 'DETALLE_COMPRA',
            },
        ),
    ]
