# Generated by Django 6.0.3 on 2026-05-30 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0007_tipometal_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('stock_actual_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_metal', models.ForeignKey(db_column='id_metal', on_delete=django.db.models.deletion.PROTECT, to='reciclaje.tipometal')),
                ('id_usuario_responsable', models.ForeignKey(blank=True, db_column='id_usuario_responsable', null=True, on_delete=django.db.models.deletion.PROTECT, to='reciclaje.usuario')),
            ],
            options={
                'db_table': 'INVENTARIO',
            },
        ),
    ]
